name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Update npm to latest version for OIDC support
        run: pnpm add -g npm@latest
      - run: npm publish --provenance
